Parameters:
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'
Resources:
  PlanningPokerEc2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: planning-poker
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: PlanningPokerApplication
      SecurityGroups:
        - !Ref PlanningPokerSecurityGroup
      UserData: !Base64 |
        #cloud-boothook
        #!/bin/bash
        sudo yum -y install java-17-amazon-corretto-headless
        aws s3 cp s3://planning-poker-application/planning-poker-jvm-0.0.2.jar .
        sudo java -jar planning-poker-jvm-0.0.2.jar &
  PlanningPokerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the Planning Poker application
      GroupName: planning-poker-sg
      SecurityGroupIngress:
        - Description: Allow all ingress
          CidrIp: 0.0.0.0/0
          IpProtocol: -1
          FromPort: -1
          ToPort: -1
  PlanningPokerEip:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref PlanningPokerEc2
